blog/urls.py
from django.urls import path, include
from blog.views import (
    BlogList,
    BlogDetail,
    CommentCreate,
    BlogSearch,
)
from blog.feeds import LatestEntriesFeed

app_name = "blog"

urlpatterns = [
    path("", BlogList.as_view(), name="index"),
    path("<int:pk>", BlogDetail.as_view(), name="detail"),
    # path("<int:pk>/comment-create", CommentCreate.as_view(), name="comment-create"),
    path("category/<str:cat_name>", BlogList.as_view(), name="category"),
    path("tag/<str:tag_name>", BlogList.as_view(), name="tag"),
    # path('author/<str:author_username>' , BlogList.as_view(), name='author'),
    path("search/", BlogSearch.as_view(), name="search"),
    path("rss/feed/", LatestEntriesFeed()),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    re_path(r"^robots\.txt", include("robots.urls")),
    re_path(r"^ckeditor/", include("ckeditor_uploader.urls")),  # The CKEditor path

]

# admin interface Header
admin.site.site_header = 'UBPC'
admin.site.index_title = 'Admin Panel'

# serving static and media for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from .views import (
    IndexView,
    ContactView,
    CreateTeam,
    TermsView,
    CountdownView,
    SuccessView,
)

app_name = "website"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("contact", ContactView.as_view(), name="contact"),
    path("register", CreateTeam.as_view(), name="register"),
    path("terms", TermsView.as_view(), name="terms"),
    path("countdown", CountdownView.as_view(), name="countdown"),
    path("success", SuccessView.as_view(), name="success"),
]

website/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.validators import RegexValidator
# Create your models here.


class Team(models.Model):
    team_name = models.CharField(max_length=255, verbose_name="نام تیم")
    university = models.CharField(max_length=255, verbose_name="نام دانشگاه", null=True, blank=True)
    language = models.CharField(max_length=120, verbose_name="زبان برنامه نویسیس")
    agree = models.BooleanField(default=False, verbose_name="موافقت نامه")
    GENDER_CHOICES = [
        ('M', 'مرد'),
        ('F', 'زن'),
    ]
    EDUCATION_CHOICES = [
        ('1', 'دانش آموز'),
        ('2', 'دانشجو'),
        ('3', 'دانش آموخته'),
        ('4', 'هیچکدام'),
    ]
    first_name1 = models.CharField(max_length=255)
    last_name1 = models.CharField(max_length=255)
    gender1 = models.CharField(max_length=1, choices=GENDER_CHOICES)
    phone1 = models.CharField(
        max_length=11,
        validators=[RegexValidator(r'^\d{11}$', 'Enter a valid 11-digit phone number.')]
    )
    email1 = models.CharField(max_length=255)
    education1 = models.CharField(max_length=1, choices=EDUCATION_CHOICES, null=True, blank=True)
    major1 = models.CharField(max_length=255, null=True, blank=True)
    student_number1 = models.CharField(max_length=20, null=True, blank=True)

    first_name2 = models.CharField(max_length=255)
    last_name2 = models.CharField(max_length=255)
    gender2 = models.CharField(max_length=1, choices=GENDER_CHOICES)
    phone2 = models.CharField(
        max_length=11,
        validators=[RegexValidator(r'^\d{11}$', 'Enter a valid 11-digit phone number.')]
    )
    email2 = models.CharField(max_length=255)
    education2 = models.CharField(max_length=1, choices=EDUCATION_CHOICES, null=True, blank=True)
    major2 = models.CharField(max_length=255, null=True, blank=True)
    student_number2 = models.CharField(max_length=20, null=True, blank=True)

    first_name3 = models.CharField(max_length=255, null=True, blank=True)
    last_name3 = models.CharField(max_length=255, null=True, blank=True)
    gender3 = models.CharField(max_length=1, choices=GENDER_CHOICES, null=True, blank=True)
    phone3 = models.CharField(max_length=11, null=True, blank=True)
    email3 = models.CharField(max_length=255, null=True, blank=True)
    education3 = models.CharField(max_length=1, choices=EDUCATION_CHOICES, null=True, blank=True)
    major3 = models.CharField(max_length=255, null=True, blank=True)
    student_number3 = models.CharField(max_length=20, null=True, blank=True)


    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_date", "team_name", "language"]
        verbose_name = "تیم"
        verbose_name_plural = "تیم ها"
    def __str__(self):
        return self.team_name


class Contact(models.Model):
    name = models.CharField(max_length=80)
    email = models.EmailField()
    subject = models.CharField(max_length=100, null=True, blank=True, default=None)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_date"]

    def __str__(self):
        return "{} - {}".format(self.name, self.subject)


class Newsletter(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

website/views.py
from django.views.generic import (
    ListView,
    CreateView,
)
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin

from .models import Contact, Team
from blog.models import Post


# Create your views here.


class IndexView(ListView):
    model = Team
    template_name = "website/index.html"
    context_object_name = "teams"

    def get_queryset(self):
        # return all the Team objects
        return self.model.objects.all()

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        posts = Post.objects.all().order_by("-created_date")[:6]
        context.update(
            {
                "posts": posts,
            }
        )
        return context

class CreateTeam(SuccessMessageMixin, CreateView):
    model = Team
    template_name = "website/register.html"
    success_url = reverse_lazy("website:success")
    
    fields = [
        "team_name",
        "university",
        "language",
        # person 1
        "first_name1",
        "last_name1",
        "gender1",
        "phone1",
        "email1",
        "education1",
        "student_number1",
        # person 2
        "first_name2",
        "last_name2",
        "gender2",
        "phone2",
        "email2",
        "education2",
        "student_number2",
        # person 3
        "first_name3",
        "last_name3",
        "gender3",
        "phone3",
        "email3",
        "education3",
        "student_number3",
        "agree",
    ]
    success_message = ".تیم شما با موفقیت ثبت شد. لطفا برای پرداخت هزینه ورودی به اطلاعیه ها مراجعه کنید "
    def form_valid(self, form):
        return super().form_valid(form)

class SuccessView(ListView):
    model = Team
    template_name = "website/successful.html"
    context_object_name = "teams"


class ContactView(CreateView):
    model = Contact
    template_name = "website/contact.html"
    success_url = reverse_lazy("website:index")
    # form_class = CreateContactForm
    fields = [
        "name",
        "email",
        "subject",
        "message",
    ]

    def form_valid(self, form):
        return super().form_valid(form)

class TermsView(ListView):

    model = Team
    template_name = "website/terms.html"
    context_object_name = "teams"

    def get_queryset(self):
        # return all the Team objects
        return self.model.objects.all()
    
class CountdownView(ListView):

    model = Team
    template_name = "website/countdown.html"
    context_object_name = "teams"

    def get_queryset(self):
        # return all the Team objects
        return self.model.objects.all()
    

templates/website/widgets/recent-posts.html
{% load static %}
{% load thumbnail %}


<!-- 
    usage:
    {% include 'website/widgets/recent-posts.html' %}
 -->
<!-- services card section-->
<div class="services-card-section spad">
    <div class="container">
        <div class="row">
            {% for post in posts %}
            <!-- Single Card -->
            <div class="col-md-4 col-sm-6"  style="margin-top: 2%;">
                <div class="sv-card">
                    <a href="{% url 'blog:detail' pk=post.id %}">
                        <div class="card-img">
                            {% thumbnail post.image "1280x720" crop="center" as im %}
                            <img src="{{ im.url }}" max-width="{{ im.width }}" max-height="{{ im.height }}" alt=""
                                class="img-fluid">
                            {% endthumbnail %}
                        </div>
                    </a>
                    <div class="card-text">
                        <h2><a href="{% url 'blog:detail' pk=post.id %}">{{post.title}}</a></h2>
                        <h6>{{post.category.first}}</h6>
                        <p>{{post.summary}}</p>
                        <span style="display: flex;
                        align-items: center; gap: 4px;">
                            <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 496 512">
                                <path
                                    d="M248 8C111 8 0 119 0 256s111 248 248 248 248-111 248-248S385 8 248 8zm0 96c48.6 0 88 39.4 88 88s-39.4 88-88 88-88-39.4-88-88 39.4-88 88-88zm0 344c-58.7 0-111.3-26.6-146.5-68.2 18.8-35.4 55.6-59.8 98.5-59.8 2.4 0 4.8.4 7.1 1.1 13 4.2 26.6 6.9 40.9 6.9 14.3 0 28-2.7 40.9-6.9 2.3-.7 4.7-1.1 7.1-1.1 42.9 0 79.7 24.4 98.5 59.8C359.3 421.4 306.7 448 248 448z" />
                            </svg>
                             {{post.author.first_name}} {{post.author.last_name}} </span>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
<!-- services card section end-->