blog/urls.py
from django.urls import path, include
from blog.views import (
    BlogList,
    BlogDetail,
    CommentCreate,
    BlogSearch,
)
from blog.feeds import LatestEntriesFeed

app_name = "blog"

urlpatterns = [
    path("", BlogList.as_view(), name="index"),
    path("<int:pk>", BlogDetail.as_view(), name="detail"),
    # path("<int:pk>/comment-create", CommentCreate.as_view(), name="comment-create"),
    path("category/<str:cat_name>", BlogList.as_view(), name="category"),
    path("tag/<str:tag_name>", BlogList.as_view(), name="tag"),
    # path('author/<str:author_username>' , BlogList.as_view(), name='author'),
    path("search/", BlogSearch.as_view(), name="search"),
    path("rss/feed/", LatestEntriesFeed()),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    re_path(r"^robots\.txt", include("robots.urls")),
    re_path(r"^ckeditor/", include("ckeditor_uploader.urls")),  # The CKEditor path

]

# admin interface Header
admin.site.site_header = 'UBPC'
admin.site.index_title = 'Admin Panel'

# serving static and media for development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from .views import (
    IndexView,
    ContactView,
    CreateTeam,
    TermsView,
    CountdownView,
    SuccessView,
)

app_name = "website"

urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("contact", ContactView.as_view(), name="contact"),
    path("register", CreateTeam.as_view(), name="register"),
    path("terms", TermsView.as_view(), name="terms"),
    path("countdown", CountdownView.as_view(), name="countdown"),
    path("success", SuccessView.as_view(), name="success"),
]

blog/models.py
from django.db import models

# from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager
from ckeditor_uploader.fields import RichTextUploadingField
from django.core.exceptions import ValidationError
from blog.formatChecker import ContentTypeRestrictedFileField


# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=60)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Post(models.Model):
    def validate_image(fieldfile_obj):
        filesize = fieldfile_obj.file.size
        megabyte_limit = 2.0
        if filesize > megabyte_limit * 1024 * 1024:
            raise ValidationError("Max image size is %sMB" % str(megabyte_limit))

    image = models.ImageField(
        upload_to="blog/", default="blog/default.jpg", validators=[validate_image]
    )
    author = models.ForeignKey("accounts.Profile", on_delete=models.SET_NULL, null=True)
    title = models.CharField(max_length=100)
    summary = models.TextField(blank=True)
    content = RichTextUploadingField()  # CKEditor Rich Text Field
    audio = ContentTypeRestrictedFileField(
        upload_to="uploads/",
        content_types=["audio/mpeg"],
        max_upload_size=20971520,
        blank=True,
        null=True,
        verbose_name="audio",
    )  # 'video/x-msvideo', 'application/pdf', 'video/mp4',
    video = ContentTypeRestrictedFileField(
        upload_to="uploads/",
        content_types=["video/mp4"],
        max_upload_size=20971520,
        blank=True,
        null=True,
        verbose_name="video",
    )
    category = models.ManyToManyField(Category)
    tags = TaggableManager()
    estimated_time = models.PositiveIntegerField(
        default=10, verbose_name="Estimated time (minutes)"
    )
    counted_views = models.PositiveIntegerField(default=0)

    counted_likes = models.PositiveIntegerField(default=0)

    publish_status = models.BooleanField(
        default=False,
    )
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created_date",)

    def __str__(self):
        return "{} - {}".format(self.title, self.id)

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"pk": self.id})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=70)
    email = models.EmailField()
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created_date",)

    def approve(self):
        self.approved = True
        self.save()

    def get_absolute_url(self):
        return reverse("blog:detail", kwargs={"pk": self.post.id})

    def __str__(self):
        return self.post.title

blog/forms.py
# from django.forms import ModelForm
# from blog.models import Comment

# # from captcha.fields import CaptchaField


# class CommentForm(ModelForm):
#     # captcha = CaptchaField()
#     def __init__(self, *args, **kwargs):
#         super(CommentForm, self).__init__(*args, **kwargs)

#     class Meta:
#         model = Comment
#         fields = ["post", "name", "email", "message"]

blog/views.py
from django.utils import timezone

# from django.contrib import messages
from django.views.generic import (
    ListView,
    CreateView,
)
from .models import Post, Comment

# from blog.forms import CommentForm

# Create your views here.


class BlogList(ListView):
    model = Post
    template_name = "blog/blog-list.html"
    context_object_name = "posts"

    def get_queryset(self):
        # return all the comment objects from a specified post
        posts = Post.objects.filter(published_date__lte=timezone.now()).order_by(
            "-published_date"
        )

        for post in posts:  # turn publish_status on(Ture) if published_date is passed
            if post.publish_status is False:
                post.publish_status = True
                post.save()
        if self.kwargs.get("cat_name") is not None:  # posts by category
            posts = posts.filter(category__name=self.kwargs["cat_name"])

        # if kwargs.get('author_username') != None:
        #     posts = posts.filter(author__username=kwargs['author_username'])

        if self.kwargs.get("tag_name") is not None:
            posts = posts.filter(tags__name__in=[self.kwargs["tag_name"]])
        return posts

    paginate_by = 4

    def get_context_data(self, **kwargs):
        context = super(BlogList, self).get_context_data(**kwargs)
        if not context.get("is_paginated", False):
            return context
        # Custom Pagination
        paginator = context.get("paginator")
        num_pages = paginator.num_pages
        current_page = context.get("page_obj")
        page_no = current_page.number

        if num_pages <= 5 or page_no <= 3:  # case 1 and 2
            pages = [x for x in range(1, min(num_pages + 1, 5))]
        elif page_no > num_pages - 3:  # case 4
            pages = [x for x in range(num_pages - 4, num_pages + 1)]
        else:  # case 3
            pages = [x for x in range(page_no - 2, page_no + 3)]

        # first and last page
        first_page = 1
        last_page = num_pages

        context.update(
            {
                "pages": pages,
                "first_page": first_page,
                "last_page": last_page,
                "current_page": page_no,
                "page_count": num_pages,
            }
        )
        return context


class BlogDetail(ListView):
    model = Comment
    template_name = "blog/blog-details.html"
    context_object_name = "comments"

    def get_queryset(self):
        # return all the comment objects from a specified post
        post_id = self.kwargs["pk"]
        post = Post.objects.get(id=post_id)
        return self.model.objects.filter(post=post, approved=True)

    def get_context_data(self, **kwargs):
        context = super(BlogDetail, self).get_context_data(**kwargs)
        post = Post.objects.get(id=self.kwargs["pk"])
        context.update(
            {
                "post": post,
            }
        )
        return context


class CommentCreate(CreateView):
    model = Comment
    template_name = "blog/blog-details.html"
    fields = [
        "message",
        "name",
        "email",
    ]

    def form_valid(self, form):
        form.instance.post = Post.objects.get(id=self.kwargs["pk"])
        return super().form_valid(form)


class BlogSearch(ListView):
    model = Post
    template_name = "blog/blog-list.html"
    context_object_name = "posts"

    def get_queryset(self):
        # return all related posts
        posts = Post.objects.filter(published_date__lte=timezone.now())
        if s := self.request.GET.get("s"):
            posts = posts.filter(summary__contains=s) | posts.filter(title__contains=s)
        return posts

templates/blog/blog-details.html
{% extends 'base.html' %}
{% load static %}
{% load jalali_filters %}
<!-- <title>  -->
{% block title %}{{post.title}}{% endblock %}
<!-- <extra css>-->
{% block extra_css %}{% endblock %}

<!-- <body> -->

{% block content %}


	<!-- Header section -->
	<header class="header-section">
		<div class="logo">
			<img src="{% static 'pics/logo.png' %}" alt=""><!-- Logo -->
		</div>
		<!-- Navigation -->
		<div class="responsive"><i class="fa fa-bars"></i></div>
		<nav>
			<ul class="menu-list">
				<li><a href="{% url 'website:index' %}">صفحه نخست</a></li>
				<li><a href="{% url 'website:register' %}">ثبت نام</a></li>
				<li class="active"><a href="{% url 'blog:index' %}">بلاگ</a></li>
				<li><a href="{% url 'website:countdown' %}">زمان برگزاری</a></li>
				<li><a href="{% url 'website:terms' %}">شرایط و قوانین</a></li>
				<li><a href="{% url 'website:contact' %}">تماس با ما</a></li>
			</ul>
		</nav>
	</header>
	<!-- Header section end -->


	<!-- Page header -->
	<div class="page-top-section">
		<div class="overlay"></div>
		<div class="container text-right">
			<div class="page-info">
				<h2>بلاگ</h2>
				<div class="page-links">
					<a href="#" style="background-color: rgba(240, 248, 255, 0);">صفحه نخست</a>
					<span style="color: #e0f6ff;">{{post.title}}</span>
				</div>
			</div>
		</div>
	</div>
	<!-- Page header end-->


	<!-- page section -->
	<div class="page-section spad">
		<div class="container">
			<div class="row">
				<div class="col-md-12 col-sm-7 blog-posts">
					<!-- Single Post -->
					<div class="single-post">
						<div class="post-thumbnail">
							<img src="{% static 'pics/blog/bg01.jpg' %}" alt="">
							<div class="post-date">
								<h2>{{post.created_date|jalali_day}}</h2>
								<h3>{{post.created_date|jalali_month_name}} {{post.created_date|jalali_year}}</h3>
							</div>
						</div>
						<div class="post-content">
							<h2 class="post-title">{{post.title}}</h2>
							<!-- <div class="post-meta">
								<a href="">نام و نام خانوادگی</a>
								<a href="">دسته بندی</a>
								<a href="">2 کامنت</a>
							</div> -->
							{{post.summary}}
							{{post.content|safe}}
							</div>
						<!-- Post Author -->
						<!-- <div class="author">
							<div class="avatar">
								<img src="{% static 'pics/avatar/03.jpg' %}" alt="">
							</div>
							<div class="author-info">
								<h2>نام و نام خانوادگی<span> سمت</span></h2>
								<p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد</p>
							</div>
						</div> -->
						
					</div>
				</div>

			</div>
		</div>
	</div>
	<!-- page section end-->



{% endblock %}
<!-- </body> -->

<!-- <extra js>-->
{% block extra_js %}{% endblock %}

templates/blog/blog-list.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% load jalali_filters %}
<!-- <title>  -->
{% block title %}Blog{% endblock %}
<!-- <extra css>-->
{% block extra_css %}{% endblock %}

<!-- <body> -->

{% block content %}


<!-- Header section -->
<header class="header-section">
	<div class="logo" dir="rtl">
		<img src="{% static 'pics/logo.png' %}" alt=""><!-- Logo -->
	</div>
	<!-- Navigation -->
	<div class="responsive"><i class="fa fa-bars"></i></div>
	<nav>
		<ul class="menu-list">
			<li><a href="{% url 'website:index' %}">صفحه نخست</a></li>
			<li><a href="{% url 'website:register' %}">ثبت نام</a></li>
			<li class="active"><a href="{% url 'blog:index' %}">بلاگ</a></li>
			<li><a href="{% url 'website:countdown' %}">زمان برگزاری</a></li>
			<li><a href="{% url 'website:terms' %}">شرایط و قوانین</a></li>
			<li><a href="{% url 'website:contact' %}">تماس با ما</a></li>
		</ul>
		
	</nav>
</header>
<!-- Header section end -->


<!-- Page header -->
<div class="page-top-section">
	<div class="overlay"></div>
	<div class="container text-right">
		<div class="page-info">
			<h2>بلاگ</h2>
			<div class="page-links">
				<a href="#" style="background-color: rgba(240, 248, 255, 0);">صفحه نخست</a>
				<span>بلاگ</span>
			</div>
		</div>
	</div>
</div>
<!-- Page header end-->


<!-- page section -->
<div class="page-section spad">
	<div class="container">
		<div class="row">
			<div class="col-md-8 col-sm-7 blog-posts">
				<!-- Post item -->
				{% for post in posts %}
				<div class="post-item">
					<div class="post-thumbnail">
						{% thumbnail post.image "1280x720" crop="center" as im %}
						<img src="{{ im.url }}" max-width="{{im.width}}" max-height="{{im.height}}" alt=""
							class="img-fluid">
						{% endthumbnail %}
						<div class="post-date">
							<h2>{{post.created_date|jalali_day}}</h2>
							<h3>{{post.created_date|jalali_month_name}} {{post.created_date|jalali_year}}</h3>
						</div>
					</div>
					<div class="post-content">
						<a href="{% url 'blog:detail' pk=post.id %}">
							<h2 class="post-title">{{post.title}}</h2>
						</a>

						<p>{{post.summary}}</p>
						<a href="{% url 'blog:detail' pk=post.id %}" class="read-more">بیشتر بخوانید</a>
					</div>
				</div>
				{% endfor %}
				<!-- Pagination -->

				<!-- <div class="page-pagination">
						<a class="active" href="">01.</a>
						<a href="">02.</a>
						<a href="">03.</a>
					</div> -->


				{% if page_obj.has_other_pages %}
				<!-- pagination -->
				<div class="page-pagination">
					<ul>

						<!-- previous and first page -->
						{% if current_page != 1 %}
						<a href="/blog/?page={{page_obj.previous_page_number}}">
							
								< 
						</a>

						{% if current_page != 2 %}
						<a href="/blog/?page=1">
							 First 
						</a>
						{% endif %}
						{% endif %}
						<!-- end -->

						<!-- pagination numbers -->
						{% for i in pages %}
						{% if current_page == i %}
						<a class="is-active" href="/blog/?page={{i}}">
							{{i}}
						</a>
						{% else %}
						<a href="/blog/?page={{i}}">
							{{i}}
						</a>
						{% endif %}
						{% endfor %}
						<!-- end -->

						<!-- next and last page -->
						{% if page_obj.has_next %}
						<a href="/blog/?page={{page_obj.next_page_number}}">
							>
						</a>
						{% if last_page != 1 %}
						<a href="/blog/?page={{last_page}}">
							 Last
						</a>
						{% endif %}

						{% endif %}
						<!-- end -->

					</ul>
				</div>
				<!-- pagination ends -->
				</main><!-- End #main -->
				{% endif %}



			</div>
		</div>
	</div>
</div>
<!-- page section end-->



{% endblock %}
<!-- </body> -->

<!-- <extra js>-->
{% block extra_js %}{% endblock %}